[package]
name = "photon"
version = "0.1.0"
authors = ["silvi <silviaodwyerdev@gmail.com>"]
edition = "2018"

[dependencies]
image = "*"
rand = "*"
time = "*"
palette = "0.4.1"
num = "0.2.0"
imageproc="*"
rusttype="*"
raster="*"